/**
 * This is an example of how to create a template that makes use of streams data.
 * The stream data originates from Yext's Knowledge Graph. When a template in
 * concert with a stream is built by the Yext Sites system, a static html page
 * is generated for every corresponding (based on the filter) stream document.
 *
 * Another way to think about it is that a page will be generated using this
 * template for every eligible entity in your Knowledge Graph.
 */

import * as React from "react";
import Banner from "../components/banner";
import Cta from "../components/cta";
import Contact from "../components/contact";
import List from "../components/list";
import Hours from "../components/hours";
import StaticMap from "../components/static-map";
import "../index.css";
import {
  Template,
  GetPath,
  GetRedirects,
  TemplateConfig,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
} from "@yext/pages";
import PageLayout from "../components/page-layout";
import Locations_mcD from "../components/locations_mcD";
import parsePhoneNumber from "libphonenumber-js";
import { Carousel } from "@trendyol-js/react-carousel";
import {
  Accordion,
  AccordionItem,
  AccordionItemButton,
  AccordionItemHeading,
  AccordionItemPanel,
} from "react-accessible-accordion";

/**
 * Required when Knowledge Graph data is used for a template.
 */
export const config: TemplateConfig = {
  stream: {
    $id: "my-stream-id-1",
    // Specifies the exact data that each generated document will contain. This data is passed in
    // directly as props to the default exported function.
    fields: [
      "id",
      "uid",
      "meta",
      "name",
      "address",
      "mainPhone",
      "description",
      "hours",
      "slug",
      "geocodedCoordinate",
      "services",
      "c_locationToMenu.name",
      "c_locationToMenu.photoGallery",
      "c_locationToMenu.price",
      "pickupAndDeliveryServices",
    ],
    // Defines the scope of entities that qualify for this stream.
    filter: {
      entityTypes: ["location"],
    },
    // The entity language profiles that documents will be generated for.
    localization: {
      locales: ["en"],
      primary: false,
    },
  },
};

/**
 * Defines the path that the generated file will live at for production.
 *
 * NOTE: This currently has no impact on the local dev path. Local dev urls currently
 * take on the form: featureName/entityId
 */
export const getPath: GetPath<TemplateProps> = ({ document }) => {
  return document.slug
    ? document.slug
    : `${document.locale}/${document.address.region}/${document.address.city}/${
        document.address.address1
      }-${document.id.toString()}`;
};

/**
 * Defines a list of paths which will redirect to the path created by getPath.
 *
 * NOTE: This currently has no impact on the local dev path. Redirects will be setup on
 * a new deploy.
 */
export const getRedirects: GetRedirects<TemplateProps> = ({ document }) => {
  return [`index-old/${document.id.toString()}`];
};

/**
 * This allows the user to define a function which will take in their template
 * data and procude a HeadConfig object. When the site is generated, the HeadConfig
 * will be used to generate the inner contents of the HTML document's <head> tag.
 * This can include the title, meta tags, script tags, etc.
 */
export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({
  relativePrefixToRoot,
  path,
  document,
}): HeadConfig => {
  return {
    title: document.name,
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "meta",
        attributes: {
          description: "This site was generated by the Yext SSG",
        },
      },
    ],
  };
};
const faqOptions = [
  {
    heading: "Does Denny’s offer delivery?",
    content:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
  },
  {
    heading: "Where is The Burger Den located?",
    content:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
  },
  {
    heading: "Is The Burger Den available in my area?",
    content:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
  },
  {
    heading: "Where is The Meltdown located?",
    content:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
  },
  {
    heading: "Is The Meltdown available in my area?",
    content:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
  },
];
/**
 * This is the main template. It can have any name as long as it's the default export.
 * The props passed in here are the direct stream document defined by `config`.
 *
 * There are a bunch of custom components being used from the src/components folder. These are
 * an example of how you could create your own. You can set up your folder structure for custom
 * components any way you'd like as long as it lives in the src folder (though you should not put
 * them in the src/templates folder as this is specific for true template files).
 */
const Location: Template<TemplateRenderProps> = ({
  relativePrefixToRoot,
  path,
  document,
}) => {
  const {
    _site,
    name,
    address,
    openTime,
    hours,
    mainPhone,
    geocodedCoordinate,
    services,
    c_locationToMenu,
    pickupAndDeliveryServices,
  } = document;
  const phoneNumber = parsePhoneNumber(mainPhone);

  return (
    <>
      {pickupAndDeliveryServices && pickupAndDeliveryServices.length >= 1 ? (
        <>
          <div className="headerStyle mt-4">
            <img
              src="/src/assets/images/header.png"
              alt=""
              className="nav rounded-full"
            />

            <ol className="c-bread-crumbs-list mt-10  rounded-full">
              <li>Locations</li>
              <li>{address.region}</li>
              <li>{address.city}</li>
              <li>{name}</li>
            </ol>
            <div className="hero mt-10">
              <div className="hero-row">
                <h1>Delivery at {name}</h1>
              </div>
            </div>
            <div className="hero mt-10">
              <div className="hero-row">
                <div className="Hero-hoursToday">
                  Closed - Opens at 7:00 AM Tuesday
                </div>
              </div>
            </div>
            <div className="hero mt-10">
              <div className="flex gap-24	heroCtas">
                <Cta
                  buttonText="Get Directions"
                  url="#"
                  style="primary-cta bannerCta"
                ></Cta>
                <Cta
                  buttonText="Order now"
                  url="#"
                  style="primary-cta bannerCta"
                ></Cta>
              </div>
            </div>
          </div>
          <div className="centered-container">
            <div className="appPromo flex space-between">
              <div className="napDetails">
                <div className="details">
                  <div className="nap">
                    <h3>
                      {name} <br />
                      {address.city}, {address.region} {address.postalCode}
                    </h3>
                  </div>
                  <div className="mt-4">
                    <h3>Phone</h3>
                    <div className="phNo">
                      {phoneNumber && phoneNumber.formatNational()}
                    </div>
                  </div>
                  {hours && <Hours title={"Hours"} hours={hours} />}
                </div>
              </div>
              <div
                className="appImage"
                style={{
                  minWidth: "700px",
                  maxWidth: " 700px",
                  zIndex: "1",
                  borderRadius: "5%",
                }}
              >
                {geocodedCoordinate && (
                  <StaticMap
                    latitude={geocodedCoordinate.latitude}
                    longitude={geocodedCoordinate.longitude}
                  ></StaticMap>
                )}
              </div>
            </div>
          </div>
          <div style={{ height: "5rem", backgroundColor: "#f36c13" }}>
            <div
              style={{
                borderBottomRightRadius: "5.9375rem",
                height: "100%",
                backgroundColor: "white !important",
              }}
            ></div>
          </div>
          <div className="section p-4  bannerContent">
            <h1>Dinner Delivery Services at {name}</h1>
            <div
              className="flex gap-10 mt-10"
              style={{
                height: "555px",
                justifyContent: "center",
                textAlign: "center",
              }}
            >
              <div style={{ height: "300px", width: "300px" }}>
                <img
                  src="https://www.nrn.com/sites/nrn.com/files/Denny_s_BurgerDen-Logo-OnWhite.jpg"
                  alt=""
                  style={{
                    width: "auto",
                    height: "300px",
                    marginLeft: "auto",
                    marginRight: "auto",
                  }}
                />
                <div className="mt-4">
                  With a focus on high-quality ingredients and big, bold flavor
                  combinations, The Burger Den is cookin’ up the classics you
                  expect—and the crafty concoctions you don’t—and then
                  partnering with your favorite delivery apps.
                </div>
                <div className="w-30 mt-10">
                  <Cta
                    buttonText="Order Online"
                    url="#"
                    style="primary-cta bannerCta"
                  ></Cta>
                </div>
              </div>
              <div style={{ height: "300px", width: "300px" }}>
                <img
                  src="https://www.nrn.com/sites/nrn.com/files/Denny_s_TheMeltdown-Logo-RGB.jpg"
                  alt=""
                  style={{
                    width: "auto",
                    height: "300px",
                    marginLeft: "auto",
                    marginRight: "auto",
                  }}
                />
                <div className="mt-4">
                  From a love of all things cheesy and the idea that mealtime
                  should fit your mood, The Meltdown is the new go-to for
                  handcrafted melts with fresh ingredients and a side of
                  attitude.
                </div>
                <div className="w-30 mt-10">
                  <Cta
                    buttonText="Order Online"
                    url="#"
                    style="primary-cta bannerCta"
                  ></Cta>
                </div>
              </div>
            </div>
          </div>
          <div style={{ height: "5rem", backgroundColor: "#d0442b" }}>
            <div
              style={{
                borderTopRightRadius: "5.9375rem",
                height: "100%",
                backgroundColor: "white !important",
              }}
            ></div>
          </div>
          <div className="centered-container">
            <div className="appPromo flex space-between  mt-10">
              <div
                className="appImage"
                style={{
                  minWidth: "590px",
                  maxWidth: " 590px",
                  zIndex: "1",
                }}
              >
                <img
                  src="https://www.dennys.com/sites/default/files/styles/full_width_sm/public/2022-06/220310_Dennys_Curbside_Pickup_0221_v1.jpg?itok=ElM9DR9I"
                  style={{
                    borderRadius: "60px",
                  }}
                  alt=""
                />
              </div>
              <div className="appDetails">
                <div className="details">
                  <span className="eyebrow">Download the</span>

                  <h2>DENNY’S APP</h2>

                  <div className="field-item field-item__body">
                    <p>
                      Tap into sweet deals and delicious perks with the new
                      Denny’s App! Faster ordering, delivery driver tracking,
                      built-in rewards and the ability to easily save your
                      favorites is all at your fingertips.
                    </p>
                  </div>

                  <div className="mt-10">
                    <div className="badges flex gap-6">
                      <a href="https://play.google.com/store/apps/details?id=com.dennys.mobile&amp;hl=en_US&amp;gl=US">
                        <img
                          alt="Google Play"
                          src="	https://www.dennys.com/themes/custom/dennys/images/badge/google-play-store.svg"
                        />
                      </a>
                      <a href="https://apps.apple.com/us/app/dennys/id527548554">
                        <img
                          alt="App Store"
                          src="	https://www.dennys.com/themes/custom/dennys/images/badge/apple-app-store.svg"
                        />
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div style={{ height: "5rem", backgroundColor: "#f36c13" }}>
            <div
              style={{
                borderBottomRightRadius: "5.9375rem",
                height: "100%",
                backgroundColor: "white !important",
              }}
            ></div>
          </div>
          <div className="section p-4 bannerContent space-y-12 mt-10">
            <h1>Preferred Delivery Items</h1>
            <Carousel
              show={3.5}
              slide={2}
              swiping={true}
              className="mt-10 mb-10"
              useArrowKeys={true}
            >
              {c_locationToMenu.map((item: any, index: number) => {
                return (
                  <div key={index}>
                    <div>
                      <img src={item.photoGallery[0].image.url} alt="" />
                    </div>
                    <div className="name mt-4 text-xl">{item.name}</div>
                    {item.price && <div className="price">{item.price}</div>}
                    <div className="mt-10 mb-10">
                      <Cta
                        buttonText="Order Online"
                        url="#"
                        style="primary-cta bannerCta"
                      ></Cta>
                    </div>
                  </div>
                );
              })}
            </Carousel>
          </div>
          <div style={{ height: "5rem", backgroundColor: "#d0442b" }}>
            <div
              style={{
                borderTopRightRadius: "5.9375rem",
                height: "100%",
                backgroundColor: "white !important",
              }}
            ></div>
          </div>
          <div
            className="section p-4 bannerContent"
            style={{ marginTop: "2em !important" }}
          >
            <h1>General FAQs</h1>
            <Accordion allowZeroExpanded>
              {faqOptions.map((item, index: number) => (
                <AccordionItem
                  key={index}
                  className="faqAccordion mt-4
         mb-4"
                >
                  <AccordionItemHeading>
                    <AccordionItemButton>{item.heading}</AccordionItemButton>
                  </AccordionItemHeading>
                  <AccordionItemPanel>{item.content}</AccordionItemPanel>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </>
      ) : (
        <Locations_mcD document={document} />
      )}
    </>
  );
};

export default Location;
